baseURL = "https://bneil.me"
languageCode = "en-us"
title = "bneil.me"
copyright = "© bneil"
theme="archie"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

enableGitInfo = true
enableInlineShortcodes= true

paginate=3 # articles per page

[mediaTypes]
  [mediaTypes."application/rss+xml"]
    suffixes = ['xml']
  [mediaTypes.'text/gemini']
    suffixes = ['gmi']

[outputFormats]
[outputFormats.Gemini]
    name = "GEMINI"
    isPlainText = true
    isHTML = false
    mediaType = 'text/gemini'
    protocol= 'gemini://'
    permalinkable = true
    path = 'gemini/'
[outputFormats.GEMINI_RSS]
    bassName = "rss"
    isPlainText = false
    path = "/gemini/"
    mediaType = "application/rss+xml"


[outputs]
  home = ["HTML", "RSS", "GEMINI","GEMINI_RSS"]
  page = ["HTML", "GEMINI"]

[params]
	mode="light" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "learnings from a professional automation mechanic"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/bneil"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/benneil"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1


[[menu.main]]
    name = "Contact"
    identifier = "contact"
    weight = 2
    url = "/contact"

[[menu.main]]
    name = "Resume"
    identifier = "resume"
    weight = 3
    url = "/resume"

[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 4
    url = "/about"

[[menu.main]]
    name = "Blog"
    identifier = "blog"
    weight = 5
    url  = "/posts"

[[menu.main]]
    name = "Notes"
    identifier = "notes"
    weight = 6
    url  = "/tags/notes"

[[menu.main]]
    name = "Now"
    identifier = "now"
    weight = 7
    url  = "/now"

