baseURL = "https://bneil.me/"
languageCode = "en-us"
title = "bneil.me"
copyright = "© bneil"
theme="archie"

enableRobotsTXT=false

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

enableGitInfo = true
enableInlineShortcodes= true

[pagination]
  disableAliases = false
  pagerSize = 3
  path = 'page'

[mediaTypes]
  [mediaTypes."application/rss+xml"]
    suffixes = ['xml']
  [mediaTypes.'text/gemini']
    suffixes = ['gmi']

[outputFormats]
[outputFormats.Gemini]
    name = "gemini"
    isPlainText = true
    isHTML = false
    mediaType = 'text/gemini'
    protocol= 'gemini://'
    permalinkable = true
    path = '/gemini/'
[outputFormats.Gemini_Rss]
    bassName = "rss"
    isPlainText = false
    path = "/gemini/"
    mediaType = "application/rss+xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["html", "rss", "gemini","gemini_rss"]
  page = ["html", "gemini"]
  section = ["html","gemini"]
  term = ["gemini", "html"]
  taxonomy = ["gemini", "html"]

[params]
  mode="toggle" # color-mode → light,dark,toggle or auto
  useCDN=true
  subtitle = "learnings from a professional automation mechanic"
  geminiBaseUrl = "gemini://shiny.bneil.me"
  customCSS = ["css/extra.css"]

# IndieWeb Configuration
[params.indieweb]
  domain = "bneil.me" 
  [params.indieweb.webmention]
    endpoint = "https://webmention.io/api"  
    token = "" 
  [params.indieweb.resources]
    allowRemote = true  
    timeout = "30s"

# Social Tags
[[params.social]]
    name = "Github"
    icon = "github"
    url = "https://github.com/bneil"
[[params.social]]
    name = "IndieWeb Social"
    icon = "user-check"
    url = "https://indieweb.social/@bneil"
[[params.social]]
    name = "LinkedIn"
    icon = "linkedin"
    url = "https://www.linkedin.com/in/readyplayer1/"
[[params.social]]
    name = "Email"
    icon = "mail"
    url = "mailto:ben@neil-concepts.com"
[[params.social]]
    name = "Coderwall"
    icon = "code"
    url = "https://coderwall.com/bneil"
[[params.social]]
    name = "Medium"
    icon = "book"
    url = "https://medium.com/@bneil/about"
[[params.social]]
    name = "rss"
    icon = "rss"
    url = "https://bneil.me/index.xml"

# Main menu Items
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Resume"
    identifier = "resume"
    weight = 2
    url = "/resume"

[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 3
    url = "/about"

[[menu.main]]
    name = "Blog"
    identifier = "blog"
    weight = 4
    url  = "/posts"

[[menu.main]]
    name = "Notes"
    identifier = "notes"
    weight = 5
    url  = "/tags/notes"

[[menu.main]]
    name = "Now"
    identifier = "now"
    weight = 6
    url  = "/now"