baseurl = "/"
title = "Benjamin Neil" # Site title.
#theme = "coder-portfolio" # Set the theme.
theme = "anatole" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "" # Enable or disable Disqus.

[params] # theme parameters
    title="Benjamin Neil"
    author = "" # Author's nate.
    info = "AUTOMATION MECHANIC" # Author's job title or info.
    description = """
    AUTOMATION MECHANIC
    writer and coder
    """
    keywords = "blog,developer,engineer,golang,erlang,rust,scala,kubernetes,docker,personal" # Site keywords.
    avatarurl = "/images/avatar.gif" # Contain the path of the optionnal avatar in the static folder.
    profilePicture = "/images/avatar.gif"
    disableThemeSwitcher = false
    readMore = true

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.
    copyright = "2000-2021"

    # Google Site Verify
    gtagId = "UA-23046899-1"

[params.utterances]
    repo = "bneil/bneil.github.io"
    issueTerm = "question"
    theme= "github-dark-orange"


# Social links
[[params.socialIcons]]
    title = "Github"
    icon = "fab fa-github"
    url = "https://github.com/bneil"
[[params.socialIcons]]
    title = "Twitter"
    icon = "fab fa-twitter"
    url = "https://twitter.com/benneil/"
[[params.socialIcons]]
    title = "LinkedIn"
    icon = "fab fa-linkedin"
    url = "https://www.linkedin.com/in/readyplayer1/"
[[params.socialIcons]]
    title = "Email"
    icon = "fas fa-envelope"
    url = "mailto:ben@neil-concepts.com"
[[params.socialIcons]]
    title = "Coderwall"
    icon = "fas fa-code"
    url = "https://coderwall.com/bneil"
[[params.socialIcons]]
    title = "Medium"
    icon = "fab fa-medium"
    url = "https://medium.com/@bneil/about"
[[params.socialIcons]]
    title = "rss"
    icon = "fas fa-rss"
    url = "https://bneil.me/post/index.xml"

# Menu links
[[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url  = "/"

[[menu.main]]
    name = "Contact"
    identifier = "contact"
    weight = 2
    url = "/contact"

[[menu.main]]
    name = "Resume"
    identifier = "resume"
    weight = 3
    url = "/resume"

[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 4
    url = "/about"

[[menu.main]]
    name = "Blog"
    identifier = "blog"
    weight = 5
    url  = "/post"

[[menu.main]]
    name = "Notes"
    identifier = "notes"
    weight = 6
    url  = "/tags/notes"

[[menu.main]]
    name = "Now"
    identifier = "now"
    weight = 7
    url  = "/now"

