baseURL = "https://bneil.me"
languageCode = "en-us"
title = "bneil.me"
copyright = "© bneil"
theme="archie"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

enableGitInfo = true
enableInlineShortcodes= true

paginate=3 # articles per page

[mediaTypes]
  [mediaTypes."application/rss+xml"]
    suffixes = ['xml']
  [mediaTypes.'text/gemini']
    suffixes = ['gmi']

[outputFormats]
[outputFormats.Gemini]
    name = "gemini"
    isPlainText = true
    isHTML = false
    mediaType = 'text/gemini'
    protocol= 'gemini://'
    permalinkable = true
    path = '/gemini/'
[outputFormats.Gemini_Rss]
    bassName = "rss"
    isPlainText = false
    path = "/gemini/"
    mediaType = "application/rss+xml"


[outputs]
  home = ["html", "rss", "gemini","gemini_rss"]
  page = ["html", "gemini"]
  section = ["html","gemini"]
  term = ["gemini", "html"]
  taxanomy = ["gemini", "html"]


[params]
  customcss=["css/update.css"]
  mode="dark" # color-mode → light,dark,toggle or auto
  useCDN=true
  subtitle = "learnings from a professional automation mechanic"
  geminiBaseUrl = "gemini://shiny.bneil.me"

# Social Tags
[[params.social]]
    name = "Github"
    icon = "github"
    url = "https://github.com/bneil"
[[params.social]]
    name = "Twitter"
    icon = "twitter"
    url = "https://twitter.com/benneil/"
[[params.social]]
    name = "LinkedIn"
    icon = "linkedin"
    url = "https://www.linkedin.com/in/readyplayer1/"
[[params.social]]
    name = "Email"
    icon = "mail"
    url = "mailto:ben@neil-concepts.com"
[[params.social]]
    name = "Coderwall"
    icon = "code"
    url = "https://coderwall.com/bneil"
[[params.social]]
    name = "Medium"
    icon = "book"
    url = "https://medium.com/@bneil/about"
[[params.social]]
    name = "rss"
    icon = "rss"
    url = "https://bneil.me/index.xml"


# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1


[[menu.main]]
    name = "Contact"
    identifier = "contact"
    weight = 2
    url = "/contact"

[[menu.main]]
    name = "Resume"
    identifier = "resume"
    weight = 3
    url = "/resume"

[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 4
    url = "/about"

[[menu.main]]
    name = "Blog"
    identifier = "blog"
    weight = 5
    url  = "/posts"

[[menu.main]]
    name = "Notes"
    identifier = "notes"
    weight = 6
    url  = "/tags/notes"

[[menu.main]]
    name = "Now"
    identifier = "now"
    weight = 7
    url  = "/now"
