name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy To Github
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Compress action step
        id: compress
        run: |
           tar -C public/gemini/ -cvz . > site.tar.gz

      - name: curl
        uses: wei/curl@v1
        with:
          args: --oauth2-bearer "${{secrets.SRHT_TOKEN}}" -Fcontent=@site.tar.gz -Fprotocol=GEMINI https://pages.sr.ht/publish/shiny.bneil.me
